// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAhgM4OODrlwdUrKv97LQtlbQaNN35y3w',
    appId: '1:1040028038022:android:d79d5c75cd3cd9a533f207',
    messagingSenderId: '1040028038022',
    projectId: 'shagun-20c2a',
    storageBucket: 'shagun-20c2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhSnxOJ-RMr3Scq8g2_IawGlXQ2h9AV4Q',
    appId: '1:1040028038022:ios:1a9abae1c2dfd64333f207',
    messagingSenderId: '1040028038022',
    projectId: 'shagun-20c2a',
    storageBucket: 'shagun-20c2a.appspot.com',
    androidClientId: '1040028038022-n2u6a5p637uffi2vc42btb4me4gsm2do.apps.googleusercontent.com',
    iosClientId: '1040028038022-47llmmg8pjj98dj1frft416kiur2vkrg.apps.googleusercontent.com',
    iosBundleId: 'com.appisode.shagun.shagunMobile',
  );
}
